### PR TITLE
initialPhoneNumber without initialPhoneCountryPrefix on Android

### PR DESCRIPTION
**Pull request by jvthanh**
don't need required phone country prefix, it will be default by phone local country prefix.

### CODE REVIEW

**Comment by aschenkel** [comment]
Hey @jvthanh ! can I ask you what exactly do you mean by ?
>  it will be default by phone local country prefix

At the moment the `react-native-fb-account-kit` does not detects phone country prefix automatically. It is up to the one using this package to provide this param if wanted since its optional.

**Comment by jvthanh** [comment]
@aschenkel FB Account Kit SDK will detect phone country prefix automatically. So we don't need init phone country prefix as required

**Comment by aschenkel** [comment]
@jvthanh You are right! Just tested and works as expected.

In order to merge it would be nice to:

-  [ ] **Minor code adjustment**: since both `initialPhoneNumber` and `initialPhoneCountryPrefix` cannot be null due to [config default values](https://github.com/underscopeio/react-native-facebook-account-kit/blob/master/index.js#L21) all checks are unnecessary. In this way, you can handle each field setting independently (or not set them at all, which in `initialPhoneCountryPrefix` case will cause to be autodetected).

```javascript
String initialPhoneNumber = this.options.getString("initialPhoneNumber");
String initialPhoneCountryPrefix = this.options.getString("initialPhoneCountryPrefix");

PhoneNumber phoneNumber = new PhoneNumber(initialPhoneCountryPrefix, initialPhoneNumber, null);
configurationBuilder.setInitialPhoneNumber(phoneNumber); 
```


- [ ] **Add documentation**: explain this behavior on the [docs](https://github.com/underscopeio/react-native-facebook-account-kit/blob/master/README.MD#usage) where `initialPhoneCountryPrefix` usage is shown, like the following

```javascript
RNAccountKit.configure({
  ...
  initialPhoneCountryPrefix: '+1', // autodetected if none is provided
  ...
})
```



Don't mind if you `push -f` in order to avoid unnecessary extra commits

**Comment by jvthanh** [comment]
@aschenkel I just push a new commit base on your suggestion.

**Comment by aschenkel** [comment]
@jvthanh Merged! Thanks for your contribution!

**Pull request merged**
