### PR TITLE
Add Cocoapods support

### PR DESCRIPTION
**Pull request by hhunaid**
Added a podspec to link this library via cocoapods and download AccountKit as a pod dependency rather than manually linking it

### CODE REVIEW

**Comment by gaguirre** [comment]
Thanks @hhunaid! Have you tested this in a real project?

**Comment by hhunaid** [comment]
Yes I am using it in my project right now.

**Comment by gaguirre** [comment]
Great! Could you write some documentation about _how to integrate with Cocoa Pods_?

**Comment by aschenkel** [comment]
Hey @hhunaid! Thanks for the contribution. Would you mind opening a PR per feature? 
In that way it is easier for us to test and merge. 

In the case of the cocoapods support we are already handling it through [this PR](https://github.com/underscopeio/react-native-facebook-account-kit/pull/108)

Closing it due to its adds multiple unrelated features

**Pull request closed without merging**
