### PR TITLE
Update for RN@0.40.0 new header paths

### PR DESCRIPTION
**Pull request by Vrtak-CZ**
React native has made a breaking change to header paths in 0.40.0 (https://github.com/facebook/react-native/releases/tag/v0.40.0)

### CODE REVIEW

**Comment by gaguirre** [comment]
Thanks @Vrtak-CZ! I'll approve it later because I'd like to test the integration within an empty RN project.
If you want to do it would be great to have an example for 0.40 version into `examples` folder ;)

**Comment by gaguirre** [comment]
Thank you @Vrtak-CZ and @sinn1!
I can close the #59 right?

**Comment by Vrtak-CZ** [comment]
@gaguirre is it possible to release / tag new version please?

**Comment by gaguirre** [comment]
@Vrtak-CZ I just published the **0.6.0**
Thank you for letting me know!

**Comment by Vrtak-CZ** [comment]
@gaguirre thank you!

**Pull request merged**
