### PR TITLE
Added Cocoa Pods installation guide and updated .podspec

### PR DESCRIPTION
**Pull request by Jobeso**
I wanted to use this awesome package with Cocoa Pods. Therefore I updated the .podfile so the Account Kit dependency is automatically added and no drag and drop is necessary. To explain others how this kind of installation works I updated the Readme for that.
Thank for your great work!

### CODE REVIEW

**Comment by gaguirre** [comment]
Thank you for the contribution @Jobeso!
I'll check everything works OK and merge then.

**Comment by gaguirre** [comment]
Could you create a new example into `examples` folder with a RN project using this module via CocoaPods?
I just tried and get an error, so it could be really helpful to speed up the merge.

**Comment by Jobeso** [comment]
@gaguirre Hey, thanks for your response. I can create an example, not sure if I can do it today.

**Comment by aschenkel** [comment]
Hey @Jobeso ! We're looking forward to add Cocoa Pods to this package. It would be nice to accomplish that by merging your PR. In order to that we need you to:

- [ ] Correct **.podspec** `source` value to 
    _`https://github.com/underscopeio/react-native-facebook-account-kit.git`_

- [ ] Update README.md to the [following](https://raw.githubusercontent.com/underscopeio/react-native-facebook-account-kit/cocoapods/README.MD) 

- [ ] Squash multiple commits with same message into a single one

If you are unable to carry on with this at the moment we highly appreciate your contribution and will complete the task from where you left it.

**Comment by aschenkel** [comment]
Closing this one in favor of #141

**Pull request closed without merging**
