### PR TITLE
Updated compile SDK version to match Account Kit's

### PR DESCRIPTION
**Pull request by gvillenave**
Switched to 25.0.3

### CODE REVIEW

**Comment by gaguirre** [comment]
@gvillenave do you know if this introduces any issue for any platform? (Android/iOS)

**Comment by gvillenave** [comment]
It shouldn't, also I've been using this in production for a couple of weeks now and haven't experienced any issues (including on existing client devices).

**Comment by jayprakash1** [comment]
@gaguirre I have been using the same and haven't experienced any issues as mentioned earlier in https://github.com/underscopeio/react-native-facebook-account-kit/pull/79

**Comment by gaguirre** [comment]
Thank you guys, I'll test this and merge if no issues :)

**Comment by gvillenave** [comment]
@gaguirre Thanks! Any update?

**Comment by gvillenave** [comment]
Any idea when this will be merged?

**Comment by gvillenave** [comment]
Ping

**Comment by gaguirre** [comment]
Sorry for the delay @gvillenave! And thanks for being patient!
I've finally tested and will merge it right now.

**Comment by gaguirre** [comment]
I'll check if there is any other PR to merge or issue to fix before releasing a new version, but I'll publish a new one with this change these days ;)

**Comment by gaguirre** [comment]
Published version **0.9.0** 😃

**Comment by gvillenave** [comment]
Thanks!

**Pull request merged**
